# Generated by Django 3.2 on 2021-04-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authentication',
            old_name='is_former',
            new_name='is_farmer',
        ),
    ]
