# Generated by Django 3.2 on 2021-05-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.CharField(default='himana', max_length=100),
            preserve_default=False,
        ),
    ]
