# Generated by Django 3.2 on 2021-04-26 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_rename_username_farm_user_id'),
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('M', 'Medium'), ('H', 'High')], default='M', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=999999)),
                ('discount', models.FloatField()),
                ('quantity', models.FloatField()),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
                ('fruit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.fruit')),
            ],
        ),
    ]
