# Generated by Django 3.2 on 2021-05-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500, null=True)),
                ('variety', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='fruits/fruit')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
