# Generated by Django 3.2 on 2021-04-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='username',
            new_name='user_id',
        ),
    ]
