# Generated by Django 3.2 on 2021-05-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='address_id',
            new_name='pincode_id',
        ),
    ]
