# Generated by Django 3.2 on 2021-04-26 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fruits', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_payment_done', models.BooleanField(default=False)),
                ('order_time', models.TimeField(auto_now=True)),
                ('delivery_time', models.TimeField()),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.address')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.authentication')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9999999)),
                ('fruit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.fruit')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
    ]
