# Generated by Django 3.2 on 2021-05-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
