# Generated by Django 3.2 on 2021-04-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_time',
            field=models.DateTimeField(),
        ),
    ]
